# Generated by Django 5.2.8 on 2026-01-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('slots', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Zakazano'), ('completed', 'Završeno'), ('canceled', 'Otkazano')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.dentistprofile')),
                ('parent_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_appointments', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patientprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='slots.slot')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatments.treatment')),
            ],
            options={
                'ordering': ['slot__date', 'slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField(choices=[(11, 'Zub 11'), (12, 'Zub 12'), (13, 'Zub 13'), (14, 'Zub 14'), (15, 'Zub 15'), (16, 'Zub 16'), (17, 'Zub 17'), (18, 'Zub 18'), (21, 'Zub 21'), (22, 'Zub 22'), (23, 'Zub 23'), (24, 'Zub 24'), (25, 'Zub 25'), (26, 'Zub 26'), (27, 'Zub 27'), (28, 'Zub 28'), (31, 'Zub 31'), (32, 'Zub 32'), (33, 'Zub 33'), (34, 'Zub 34'), (35, 'Zub 35'), (36, 'Zub 36'), (37, 'Zub 37'), (38, 'Zub 38'), (41, 'Zub 41'), (42, 'Zub 42'), (43, 'Zub 43'), (44, 'Zub 44'), (45, 'Zub 45'), (46, 'Zub 46'), (47, 'Zub 47'), (48, 'Zub 48')])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='accounts.dentistprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='accounts.patientprofile')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatments.treatment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
